name: "Docker Compose Mender Artifact"
description: "Create a mender artifact to install docker containers using a docker-compose file."
author: "Quartx(William Forde)"
inputs:
  compose-file:
    description: "Path to docker-compose file"
    required: true
  software-name:
    description: "Name of software being packaged"
    required: true
  software-version:
    description: "Value for the software version, defaults to workflow run id"
    required: false
    default: "${{ github.run_number }}"
  device-types:
    description: "Target device type identifications, multiple values separated by a space"
    required: true
outputs:
  artifact-file:
    description: "The filename for the mender artifact file"
    value: "${{ inputs.software-name }}-${{ inputs.software-version }}.artifact.mender"
runs:
  using: "composite"
  steps:
    - name: Download mender artifact script
      run: curl https://downloads.mender.io/mender-artifact/3.6.0/linux/mender-artifact --output /usr/local/bin/mender-artifact
      shell: bash

    - name: Make artifact script executable
      run: chmod +x /usr/local/bin/mender-artifact
      shell: bash

    - name: Build artifact
      run: $GITHUB_ACTION_PATH/docker-compose-artifact-gen docker-compose.yml --device-types ${{ inputs.device-types }} --software-name ${{ inputs.software-name }} --software-version ${{ inputs.software-version }} --output-path "${{ inputs.software-name }}-${{ inputs.software-version }}.artifact.mender"
      shell: bash
branding:
  icon: 'briefcase'
  color: 'purple'
